### ISSUE TITLE
Any way to use S-Bahn lines?

### ISSUE THREAD

**Issue by fallingcats** [tofuSCHNITZEL/wienerlinien#13]
I'd like to set up a stop for S3 at Jedlersdorf but the linked website does not seem to find any stops for that line (even though the line is listed in the drop-down menu)

**Comment by tofuSCHNITZEL** [comment]
according to this file:
http://www.wienerlinien.at/ogd_realtime/doku/ogd/wienerlinien-ogd-haltepunkte.csv

found here:
http://www.wienerlinien.at/ogd_realtime/doku/

the stopID for Jedlersdorf S-Bahn is:
1089

but currently there is no info there...
maybe because now there are no trains stopping there...
you can check if there is data during the day and if so use the above stopid...
http://www.wienerlinien.at/ogd_realtime/monitor?stopid=1089

cheers

**Comment by fallingcats** [comment]
There doesn't seem to ever be data for S3 at that stop
